//! CAP-N77 — the real CEF offscreen-rendering backend (`--features cef`).
//!
//! Loads libcef (linked by `build.rs` from the pinned SDK), runs Chromium
//! windowless, and streams the paints as the `FBH1` header + fixed-size BGRA/RGBA
//! frames the app already pumps (`design/browser-host-protocol.md`). Every
//! navigation is gated through [`super::is_allowed_url`]; a redirect to
//! `file://`/`javascript:` is cancelled, not followed.
//!
//! The bindings are generated by bindgen from the C API headers, so every struct
//! layout is exact. This module is the handful of C-ABI callback structs CEF
//! drives plus the top-level run loop.
//!
//! Singletons (app/client/handlers) live for the process, so their
//! reference-count callbacks are no-ops that never free — the canonical pattern
//! for CEF handler objects owned by the host for its whole lifetime.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

use std::fs::File;
use std::io::{Read, Write};
use std::process::ExitCode;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::OnceLock;

use super::Args;

mod sys {
    //! The bindgen-generated CEF C API. Isolated so the lint noise stays here.
    #![allow(
        non_upper_case_globals,
        non_camel_case_types,
        non_snake_case,
        dead_code,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/cef_bindings.rs"));
}

use sys::*;

/// Global stop flag — the stdin watcher sets it on EOF so the run loop exits 0.
static STOP: AtomicBool = AtomicBool::new(false);
/// Stdout as a raw, unbuffered handle.
///
/// `std::io::stdout()` is a `LineWriter`, so every `write_all` scans the whole
/// buffer for a newline and splits the write around the last one. Frames are
/// binary pixel data full of `0x0A`, so that is a full extra pass over every
/// frame plus extra syscalls — ~8 MB scanned per 1080p frame to find a line
/// boundary that means nothing here. The protocol is a byte stream, never
/// lines, so write straight to the handle.
fn raw_stdout() -> &'static File {
    static OUT: OnceLock<File> = OnceLock::new();
    OUT.get_or_init(|| {
        // SAFETY: the standard output handle is owned by the process for its
        // whole lifetime, and this `File` lives in a `static` that is never
        // dropped, so it can never close a handle someone else still holds.
        #[cfg(windows)]
        unsafe {
            use std::os::windows::io::FromRawHandle;
            File::from_raw_handle(GetStdHandle(STD_OUTPUT_HANDLE))
        }
        #[cfg(not(windows))]
        unsafe {
            use std::os::fd::FromRawFd;
            File::from_raw_fd(1)
        }
    })
}

/// The FBH1 header is written to stdout exactly once, before the first frame.
static HEADER_WRITTEN: AtomicBool = AtomicBool::new(false);
/// The output geometry, captured from `Args` so `on_paint` and `get_view_rect`
/// agree (CEF may deliver a differently-sized first paint before layout settles;
/// we advertise a fixed size and trust CEF to match it).
static OUT_W: AtomicU32 = AtomicU32::new(0);
static OUT_H: AtomicU32 = AtomicU32::new(0);

/// Fill a `cef_string_utf16_t` from a Rust `&str` (UTF-8 → UTF-16 via CEF's own
/// allocator, so CEF owns and frees it).
unsafe fn set_cef_string(dst: *mut cef_string_utf16_t, s: &str) {
    // SAFETY: cef_string_utf8_to_utf16 copies into `dst` and sets its dtor.
    unsafe {
        cef_string_utf8_to_utf16(s.as_ptr() as *const std::os::raw::c_char, s.len(), dst);
    }
}

/// Read a `cef_string_userfree_t` (CEF-owned UTF-16) into a Rust String and free
/// it.
unsafe fn take_cef_string(s: cef_string_userfree_t) -> String {
    if s.is_null() {
        return String::new();
    }
    // SAFETY: `s` points at a valid cef_string_utf16_t we now own and free.
    let out = unsafe {
        let sr = &*s;
        if sr.str_.is_null() || sr.length == 0 {
            String::new()
        } else {
            String::from_utf16_lossy(std::slice::from_raw_parts(sr.str_ as *const u16, sr.length))
        }
    };
    // SAFETY: free the CEF-allocated string exactly once.
    unsafe { cef_string_userfree_utf16_free(s) };
    out
}

/// A no-op refcount for a process-lived singleton: never frees.
unsafe extern "C" fn noop_add_ref(_s: *mut _cef_base_ref_counted_t) {}
unsafe extern "C" fn noop_release(_s: *mut _cef_base_ref_counted_t) -> std::os::raw::c_int {
    0
}
unsafe extern "C" fn noop_has_one_ref(_s: *mut _cef_base_ref_counted_t) -> std::os::raw::c_int {
    0
}
unsafe extern "C" fn noop_has_at_least_one_ref(
    _s: *mut _cef_base_ref_counted_t,
) -> std::os::raw::c_int {
    1
}

/// Stamp a `cef_base_ref_counted_t` for a `T`-sized singleton with no-op counts.
fn init_base(base: &mut _cef_base_ref_counted_t, size: usize) {
    base.size = size;
    base.add_ref = Some(noop_add_ref);
    base.release = Some(noop_release);
    base.has_one_ref = Some(noop_has_one_ref);
    base.has_at_least_one_ref = Some(noop_has_at_least_one_ref);
}

// ---- Render handler: the OSR paint sink ----------------------------------

/// `get_view_rect` — advertise the fixed output size.
unsafe extern "C" fn get_view_rect(
    _self: *mut _cef_render_handler_t,
    _browser: *mut _cef_browser_t,
    rect: *mut cef_rect_t,
) {
    // SAFETY: CEF gives a valid out-param.
    unsafe {
        (*rect).x = 0;
        (*rect).y = 0;
        (*rect).width = OUT_W.load(Ordering::Relaxed) as i32;
        (*rect).height = OUT_H.load(Ordering::Relaxed) as i32;
    }
}

/// `on_paint` — write the FBH1 header once, then the fixed-size frame. CEF OSR
/// delivers BGRA top-down, `width*height*4` bytes — exactly the protocol's frame.
unsafe extern "C" fn on_paint(
    _self: *mut _cef_render_handler_t,
    _browser: *mut _cef_browser_t,
    type_: cef_paint_element_type_t,
    _dirty_count: usize,
    _dirty: *const cef_rect_t,
    buffer: *const std::os::raw::c_void,
    width: std::os::raw::c_int,
    height: std::os::raw::c_int,
) {
    // Only the main view; ignore popup widgets in v1.
    if type_ != cef_paint_element_type_t_PET_VIEW {
        return;
    }
    let (ow, oh) = (OUT_W.load(Ordering::Relaxed), OUT_H.load(Ordering::Relaxed));
    if width as u32 != ow || height as u32 != oh {
        // Layout not settled to our advertised size yet — skip this paint.
        return;
    }
    let bytes = (ow as usize) * (oh as usize) * 4;
    let mut stdout = raw_stdout();
    if !HEADER_WRITTEN.swap(true, Ordering::SeqCst) {
        let mut header = [0u8; 16];
        header[0..4].copy_from_slice(b"FBH1");
        header[4..8].copy_from_slice(&ow.to_le_bytes());
        header[8..12].copy_from_slice(&oh.to_le_bytes());
        header[12..16].copy_from_slice(&OUT_FPS.load(Ordering::Relaxed).to_le_bytes());
        if stdout.write_all(&header).is_err() {
            STOP.store(true, Ordering::SeqCst);
            return;
        }
    }
    // SAFETY: CEF guarantees `buffer` holds width*height*4 bytes for this call.
    let frame = unsafe { std::slice::from_raw_parts(buffer as *const u8, bytes) };
    // No flush: the handle is unbuffered, so write_all has already delivered it.
    if stdout.write_all(frame).is_err() {
        // The app closed the pipe — stop the loop so we exit cleanly.
        STOP.store(true, Ordering::SeqCst);
    }
}

static OUT_FPS: AtomicU32 = AtomicU32::new(30);

#[repr(C)]
struct RenderHandler {
    handler: _cef_render_handler_t,
}

impl RenderHandler {
    fn new() -> Box<Self> {
        let mut h: _cef_render_handler_t = unsafe { std::mem::zeroed() };
        init_base(&mut h.base, std::mem::size_of::<_cef_render_handler_t>());
        h.get_view_rect = Some(get_view_rect);
        h.on_paint = Some(on_paint);
        Box::new(RenderHandler { handler: h })
    }
}

// ---- Request handler: the navigation gate --------------------------------

unsafe extern "C" fn on_before_browse(
    _self: *mut _cef_request_handler_t,
    _browser: *mut _cef_browser_t,
    _frame: *mut _cef_frame_t,
    request: *mut _cef_request_t,
    _user_gesture: std::os::raw::c_int,
    _is_redirect: std::os::raw::c_int,
) -> std::os::raw::c_int {
    // SAFETY: `request` is valid; get_url returns a CEF-owned string we free.
    let url = unsafe {
        let get = (*request).get_url;
        match get {
            Some(f) => take_cef_string(f(request)),
            None => String::new(),
        }
    };
    if super::is_allowed_url(&url) {
        0 // allow
    } else {
        eprintln!("freally-browser-host: blocked navigation to {url:?}");
        1 // cancel — a redirect to file://, javascript:, etc. never proceeds
    }
}

#[repr(C)]
struct RequestHandler {
    handler: _cef_request_handler_t,
}

impl RequestHandler {
    fn new() -> Box<Self> {
        let mut h: _cef_request_handler_t = unsafe { std::mem::zeroed() };
        init_base(&mut h.base, std::mem::size_of::<_cef_request_handler_t>());
        h.on_before_browse = Some(on_before_browse);
        Box::new(RequestHandler { handler: h })
    }
}

// ---- Client: hands CEF the render + request handlers ---------------------

unsafe extern "C" fn get_render_handler(self_: *mut _cef_client_t) -> *mut _cef_render_handler_t {
    // SAFETY: `self_` is our Client; the render handler is process-lived.
    unsafe { (*(self_ as *mut Client)).render }
}

unsafe extern "C" fn get_request_handler(self_: *mut _cef_client_t) -> *mut _cef_request_handler_t {
    // SAFETY: as above.
    unsafe { (*(self_ as *mut Client)).request }
}

#[repr(C)]
struct Client {
    handler: _cef_client_t,
    render: *mut _cef_render_handler_t,
    request: *mut _cef_request_handler_t,
}

impl Client {
    fn new(render: *mut _cef_render_handler_t, request: *mut _cef_request_handler_t) -> Box<Self> {
        let mut h: _cef_client_t = unsafe { std::mem::zeroed() };
        init_base(&mut h.base, std::mem::size_of::<_cef_client_t>());
        h.get_render_handler = Some(get_render_handler);
        h.get_request_handler = Some(get_request_handler);
        Box::new(Client {
            handler: h,
            render,
            request,
        })
    }
}

// ---- App -----------------------------------------------------------------

#[repr(C)]
struct App {
    handler: _cef_app_t,
}

impl App {
    fn new() -> Box<Self> {
        let mut h: _cef_app_t = unsafe { std::mem::zeroed() };
        init_base(&mut h.base, std::mem::size_of::<_cef_app_t>());
        Box::new(App { handler: h })
    }
}

/// The CEF API version the bindings were generated against. libcef learns the
/// client's version from the FIRST call to `cef_api_hash`; without it every
/// struct is read as version -1 and libcef aborts. build.rs writes this from
/// the same constant it hands bindgen, so the two cannot drift.
include!(concat!(env!("OUT_DIR"), "/cef_api_version.rs"));

/// The app object, created once and reused by both `run_subprocess_if_any` and
/// `run` (CEF wants the same app for execute_process and initialize).
static mut APP: *mut App = std::ptr::null_mut();

/// MUST run before the host parses its own `--url`/`--width` args: CEF relaunches
/// this same executable for its GPU/renderer/utility subprocesses with `--type=`
/// arguments our parser would reject. `cef_execute_process` handles those
/// invocations and returns `>= 0` for a subprocess (we exit with that code);
/// it returns `-1` in the main browser process, where `None` lets `main`
/// continue to parse the real arguments.
pub fn run_subprocess_if_any() -> Option<ExitCode> {
    // The version handshake — the very first CEF call in the process.
    // SAFETY: documented entry point; returns a static string.
    unsafe {
        let _ = cef_api_hash(CEF_API_VERSION, 0);
    }
    let mut main_args: _cef_main_args_t = unsafe { std::mem::zeroed() };
    main_args.instance = unsafe { GetModuleHandleW(std::ptr::null()) } as *mut _;
    let app = Box::into_raw(App::new());
    // SAFETY: single write before any other access; the process is single-threaded here.
    unsafe { APP = app };

    // SAFETY: execute_process with our app; subprocesses run their loop inside.
    let code = unsafe {
        cef_execute_process(&mut main_args, app as *mut _cef_app_t, std::ptr::null_mut())
    };
    (code >= 0).then(|| ExitCode::from(code as u8))
}

/// Run the OSR host (the main browser process only). Returns the exit code.
pub fn run(args: Args) -> ExitCode {
    OUT_W.store(args.width, Ordering::Relaxed);
    OUT_H.store(args.height, Ordering::Relaxed);
    OUT_FPS.store(args.fps, Ordering::Relaxed);

    let mut main_args: _cef_main_args_t = unsafe { std::mem::zeroed() };
    main_args.instance = unsafe { GetModuleHandleW(std::ptr::null()) } as *mut _;
    // Reuse the app created in run_subprocess_if_any (the required call order).
    // SAFETY: APP was set there before main parsed args.
    let app = unsafe { APP };

    // Settings: windowless, no sandbox (the component runs unsandboxed like the
    // ffmpeg bridge), external message pump off (we drive do_message_loop_work).
    // background_color must be set BEFORE cef_initialize — it is a global default
    // the transparent/opaque page inherits.
    let mut settings: _cef_settings_t = unsafe { std::mem::zeroed() };
    settings.size = std::mem::size_of::<_cef_settings_t>();
    settings.no_sandbox = 1;
    settings.windowless_rendering_enabled = 1;
    settings.multi_threaded_message_loop = 0;
    settings.background_color = if args.transparent {
        0x0000_0000 // ARGB fully transparent
    } else {
        0xFFFF_FFFF // opaque white
    };

    // SAFETY: initialise CEF with our app; libcef is linked by build.rs.
    if unsafe {
        cef_initialize(
            &mut main_args,
            &settings,
            app as *mut _cef_app_t,
            std::ptr::null_mut(),
        )
    } == 0
    {
        eprintln!("freally-browser-host: cef_initialize failed");
        return ExitCode::from(4);
    }

    // Window info: windowless rendering. `size` MUST be set — CEF validates it
    // and rejects a zero-sized struct (create_browser_sync would return null).
    let mut window_info: _cef_window_info_t = unsafe { std::mem::zeroed() };
    window_info.size = std::mem::size_of::<_cef_window_info_t>();
    window_info.windowless_rendering_enabled = 1;

    let render = Box::into_raw(RenderHandler::new()) as *mut _cef_render_handler_t;
    let request = Box::into_raw(RequestHandler::new()) as *mut _cef_request_handler_t;
    let client = Box::into_raw(Client::new(render, request)) as *mut _cef_client_t;

    let mut browser_settings: _cef_browser_settings_t = unsafe { std::mem::zeroed() };
    browser_settings.size = std::mem::size_of::<_cef_browser_settings_t>();
    browser_settings.windowless_frame_rate = args.fps as i32;

    let mut url = cef_string_utf16_t::default();
    unsafe { set_cef_string(&mut url, args.url.trim()) };

    // SAFETY: create the OSR browser; all pointers are live for the call.
    let browser = unsafe {
        cef_browser_host_create_browser_sync(
            &window_info,
            client,
            &url,
            &browser_settings,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    };
    if browser.is_null() {
        eprintln!("freally-browser-host: could not create the OSR browser");
        unsafe { cef_shutdown() };
        return ExitCode::from(5);
    }

    // Watch stdin: EOF (the app closed our stdin) → clean shutdown.
    std::thread::spawn(|| {
        let mut buf = [0u8; 256];
        let mut stdin = std::io::stdin();
        loop {
            match stdin.read(&mut buf) {
                Ok(0) | Err(_) => {
                    STOP.store(true, Ordering::SeqCst);
                    return;
                }
                Ok(_) => {}
            }
        }
    });

    // Drive the message loop ourselves so the stop flag exits cleanly (0).
    while !STOP.load(Ordering::SeqCst) {
        unsafe { cef_do_message_loop_work() };
        std::thread::sleep(std::time::Duration::from_millis(2));
    }

    // SAFETY: tear CEF down; the singletons are leaked by design (process end).
    unsafe {
        cef_shutdown();
    }
    ExitCode::from(0)
}

// The two Win32 calls this backend needs, declared by hand rather than pulling
// in the whole `windows` crate — the host is deliberately dependency-free.
#[cfg(windows)]
const STD_OUTPUT_HANDLE: u32 = -11i32 as u32;

extern "system" {
    fn GetModuleHandleW(module: *const u16) -> *mut std::os::raw::c_void;
    #[cfg(windows)]
    fn GetStdHandle(which: u32) -> *mut std::os::raw::c_void;
}
